int Class1::Open(int flags){ int esito = 0 WriteLog(DEBUG,"Opening device [%s] [%x]",_m_path.c_str(),flags);
 if ( ( _m_fd = open( _m_path.c_str(), flags )) > 0 ) { _m_devname = _m_path;
 WriteLog(DEBUG,"Device opened fd[%d]",_m_fd);
 if( tcgetattr( _m_fd, &_m_tio ) == -1 ) { WriteLog(ERROR,"Failed to get tIO description (%s)",strerror(errno));
 return esito;
 } if( cfsetispeed(&_m_tio, BAUDRATE) == -1 ) { WriteLog(ERROR,"Failed to Set input speed (%s)",strerror(errno));
 return esito;
 } if( cfsetospeed(&_m_tio, BAUDRATE) == -1 ) { WriteLog(ERROR,"Failed to Set output speed (%s)",strerror(errno));
 return esito;
 } _m_tio.c_lflag &= ~(ECHO | ECHONL | ICANON | IEXTEN | ISIG);
 //! Non trasmissione canonica _m_tio.c_iflag &= ~(IGNBRK | BRKINT | ICRNL | INLCR | PARMRK | INPCK | IXON | IXOFF | ISTRIP);
 _m_tio.c_cflag &= ~(CSIZE | PARENB);
 _m_tio.c_cflag |= (CS8 |CREAD| CLOCAL);
//popo _m_tio.c_oflag = 0;
 // LDA &= ~(OPOST);
 _m_tio.c_cc[VMIN] =1;
 // Only 1 char to read! _m_tio.c_cc[VTIME] =0;
 // now clean the line ... if ( (tcflush(_m_fd, TCIOFLUSH) == -1) || (tcflow(_m_fd, TCIOFLUSH) == -1) || (tcsetattr(_m_fd, TCSANOW, &_m_tio) == -1) ) WriteLog(NOTICE,"serial_open(): unable to set configuration");
 else esito = _m_fd;
 } else WriteLog(ERROR,"Failed to open device %s (%s)",_m_path.c_str(),strerror(errno));
 return esito;
}Update 2: Code receiving from device

int Class1::Recv(ast_msg& a_msg){ unsigned char rec=0 int retval=0;
 bool bloop=true;
 int nLen=0, _state = 0;
 unsigned char _checksum = 0;
 unsigned char data[260];
 int idx=0;
 a_msg.clear();
 for(;
bloop;
) { WriteLog(DUMP,"Before read char");
 retval=read(_m_fd,&rec,1);
 if( retval > 0 ) { if( _state == 0 ) { idx = 0;
 } WriteLog(DUMP,"Received ;
 idx ", rec,idx);
 data[idx++]=rec;
 switch(_state) { case 0: // BOM if (rec == LUA_BOM) { _checksum = rec;
 _state++;
 } else WriteLog(WARNING,"Received ;
 idx . Expecting BOM!!!", rec,idx);
 break;
 case 1: // MSGTYPE if (MT_VBOX == (rec & 0x7F)) { _checksum ^= rec;
 _state++;
 } else { _state = 0;
 WriteLog(WARNING,"Received MsgType not MT_VBOX!", rec,idx);
 } break;
 ase 2: // NLEN if( rec 
